### ISSUE TITLE
Theme - missing <code> styles

### ISSUE THREAD

**Issue by swhalley** [peidevs/peidevs.github.io#10]
"pre" HTML tags are styled but not "code" in markdown, 
`foo` generates < code > block
```bar``` generates < pre > block.

Add some styles to < code >. This should follow similar styles to < pre > but inline, not block style. Pre also has a lot of extra padding

**Comment by evanepio** [comment]
Adding any style to code block messes with Hugo's built-in code thingy:

```
{{< highlight python "linenos=table,linenostart=1" >}}
def hello_world():
    pass

hello_world()
{{< / highlight >}}
```

More information [in Hugo's syntax highlighting docs.](https://gohugo.io/content-management/syntax-highlighting/)

This is too nice to give up. Closing this.
