### ISSUE TITLE
minor typos, grammar refactoring

### ISSUE THREAD

**Issue by codetojoy** [peidevs/peidevs.github.io#11]
- Code of Conduct [Purpose]: "We want people to feel safe and not have to be worried" could simply be "We want people to feel safe and not worry"
- Code of Conduct [The Quick Version]: "We do not tolerate" could be "We won't tolerate". (An informal contraction is used later in the paragraph, so this fits better).
- Code of Conduct [general]: it uses both "behaviour" and "behavior" (presumably cut-and-paste from American source)

**Comment by codetojoy** [comment]
- copyright date in the footer is 2017

**Comment by evanepio** [comment]
All 3 fixed
