### ISSUE TITLE
RSS Feed

### ISSUE THREAD

**Issue by swhalley** [peidevs/peidevs.github.io#12]
Hugo offers this 
http://peidevs.github.io/index.xml

should we add it to the footer?

Jordan mentions "You should add the meta tags so that readers can discover it"

**Comment by evanepio** [comment]
Hugo already does the meta tag for RSS. View source the page.

The only other tag would be something like this: `<a rel="alternate" type="application/rss+xml" href="//peidevs.github.io/index.xml">RSS Feed</a>`


Info from: https://developer.mozilla.org/en-US/docs/Web/RSS/Getting_Started/Syndicating

**Comment by evanepio** [comment]
RSS feed has been there this whole time. I just added a link to the footer.

A change to the theme was supposed to add the link, but it came with Pull Request #29
