### ISSUE TITLE
Important Links

### ISSUE THREAD

**Issue by codetojoy** [peidevs/peidevs.github.io#14]
On the website, there is a right-nav with the heading _Important Links_. In that nav, the links for _People's Scooter_ and _Scooter_ appear to be backwards.

_The People's Scooter_ is the original Dojo implementation. The newer one is Scooter (or more commonly, _The Official Scooter_).

**Comment by evanepio** [comment]
Fixed the scooter mixup, Comrade Easter!

Just need to wait for next build.
