### ISSUE TITLE
2017/2018 Sponsors

### ISSUE THREAD

**Issue by swhalley** [peidevs/peidevs.github.io#16]
Need to update logos for new sponsors

**Comment by codetojoy** [comment]
In the About/Sponsors section, the text still reads that our primary sponsor is Binary Star.

**Comment by evanepio** [comment]
I updated the sponsors to be a list instead of just Binary Star. I don't have logos, so I didn't use those.

**Comment by evanepio** [comment]
We need a build performed to get the site generated. I'm guessing we use Forestry account for that. Ran out of time for now.
