### ISSUE TITLE
revamp

### ISSUE THREAD

**Issue by codetojoy** [peidevs/peidevs.github.io#2]
Sean W has some ideas about moving from a static page/slide to a proper website

**Comment by arothmel** [comment]
Proper website :) Like that!

**Comment by swhalley** [comment]
on it. First version of the new site is now live

**Comment by evanepio** [comment]
This might be taken care of and can be closed?

**Comment by evanepio** [comment]
Yeah, this can be closed. The site is up, working and Forestry-enabled.
