### ISSUE TITLE
Make assets available over https

### ISSUE THREAD

**Issue by 2manyprojects2littletime** [peidevs/peidevs.github.io#5]
Currently the https version of the site only serves the html.  The css and js are served by http only and blocked from downloading for being mixed content.
## To repro:
- visit https://peidevs.github.io

## Expected behaviour: 
match the behaviour on http://peidev.github.io

## Actual behaviour: 

![screen shot 2017-06-29 at 10 20 33 pm](https://user-images.githubusercontent.com/6059148/27717420-55f63ee6-5d1b-11e7-9c27-99095d765956.png)
![screen shot 2017-06-29 at 9 48 51 pm](https://user-images.githubusercontent.com/6059148/27717407-42a6e458-5d1b-11e7-8fe8-15f97b25cc9f.png)

**Comment by swhalley** [comment]
I think this has to do with the baseURL of the hugo config file.
currently http://peidevs.github.io/
think it needs to be
//peidevs.github.io/

not sure how hugo will like that, but the trick works for a lot of other things

**Comment by swhalley** [comment]
I fixed this tonight and is deployed.
can you check it out again?

**Comment by swhalley** [comment]
https://github.com/peidevs/peidevs.github.io/commit/1ca41d87e45edcc5f60249ad1c6da7ad77fb06c0
