### ISSUE TITLE
Current Elders - wrong link

### ISSUE THREAD

**Issue by swhalley** [peidevs/peidevs.github.io#7]
on the code of conduct page there is a link to "current elders"
The link goes to the /about/ page which is fine but should jump to the current elders section. 

Add link tags to make this link jump down the page

**Comment by evanepio** [comment]
Looks like this will do it:

http://peidevs.github.io/about/#elders

Or if you want to go direct to current elders:

http://peidevs.github.io/about/#current-elders

**Comment by swhalley** [comment]
Oh good. I thought I may have had to use anchor tags with ids. But this is much easier
